["protostar.config"]
protostar_version = "0.3.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
early_starkers = [
    "src/early_starkers.cairo"
]
merkle = [
    "src/merkle.cairo"
]
